---
kind: pipeline
name: format
type: docker

steps:
- name: format
  image: trmckay/rust-riscv64
  commands:
    - make fmt-check

---
kind: pipeline
name: build
type: docker

steps:
- name: build
  image: trmckay/rust-riscv64
  commands:
    - make release

---
kind: pipeline
name: test
type: docker

steps:
- name: test
  image: trmckay/rust-riscv64
  commands:
    - make test

---
kind: pipeline
name: doc
type: docker

steps:
- name: build
  image: trmckay/rust-riscv64
  commands:
    - make doc

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "ln-fre-1.trmckay.com" ]
    port: 224
    delete: true
    target: /static/halogen/$DRONE_BRANCH
    source: ./kernel/target/riscv64gc-unknown-none-elf/doc/*
    key:
      from_secret: rsync-static-key
