kind: pipeline
name: check
type: docker

steps:
    - name: submodules
      image: alpine/git
      commands:
          - git submodule update --init --recursive

    - name: check
      image: trmckay/rust-riscv
      commands:
          - cargo xtask check
          - cargo xtask build

    - name: test
      image: trmckay/rust-riscv
      commands:
          - cargo xtask test 2>&1 | tee /tmp/halogen-test.out
          - if ! egrep -q '^Shutdown due to error' /tmp/halogen-test.out; then true; else false; fi
