---
kind: pipeline
name: format
type: docker

steps:
- name: format
  image: trmckay/rust-riscv64
  commands:
    - make fmt-check

---
kind: pipeline
name: build
type: docker

steps:
- name: build
  image: trmckay/rust-riscv64
  commands:
    - make release

---
kind: pipeline
name: test
type: docker

steps:
- name: test
  image: trmckay/rust-riscv64
  commands:
    - make test