---
kind: pipeline
name: style
type: docker

steps:
- name: style
  image: trmckay/rust-riscv64
  commands:
    - apt install -y python3-pip
    - pip3 install pre-commit
    - pre-commit install
    - pre-commit run trailing-whitespace -a
    - pre-commit run end-of-file-fixer -a
    - pre-commit run check-yaml -a
    - pre-commit run check-added-large-files -a
    - pre-commit run check-toml -a
    - pre-commit run check-case-conflict -a

---
kind: pipeline
name: build
type: docker

steps:
- name: build
  image: trmckay/rust-riscv64
  commands:
    - make release

---
kind: pipeline
name: test
type: docker

steps:
- name: test
  image: trmckay/rust-riscv64
  commands:
    - make test

---
kind: pipeline
name: doc
type: docker

steps:
- name: build
  image: trmckay/rust-riscv64
  commands:
    - make doc

- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "ln-fre-1.trmckay.com" ]
    port: 224
    delete: true
    target: /static/halogen/$DRONE_BRANCH
    source: ./kernel/target/riscv64gc-unknown-none-elf/doc/*
    key:
      from_secret: rsync-static-key
  when:
    event:
      - promote
    repo:
      - tm/halogen
