kind: pipeline
name: format
type: docker

steps:

- name: fmt-check
  image: rust
  commands:
    - env NONINTERACTIVE=1 make init
    - make fmt-check

---
kind: pipeline
name: build
type: docker

steps:
- name: build
  image: rust
  commands:
    - apt update && apt install -y qemu-system-riscv64
    - env NONINTERACTIVE=1 make init
    - make release

---
kind: pipeline
name: test
type: docker

steps:
- name: test
  image: rust
  commands:
    - apt update && apt install -y qemu-system-riscv64
    - env NONINTERACTIVE=1 make init
    - make test
