---
kind: pipeline
name: style
type: docker

steps:
    - name: check style
      image: trmckay/rust-riscv64
      commands:
          - cargo fmt --check
      when:
          event:
              - pull_request
              - push

---
kind: pipeline
name: build
type: docker

steps:
    - name: build
      image: trmckay/rust-riscv64
      commands:
          - make build/opensbi.bin
          - make build/halogen.bin
          - make build/halogen-test.bin
      when:
          ref:
              - refs/heads/main
              - refs/pull/*/head

    - name: test
      image: trmckay/rust-riscv64
      commands:
          - make test
      when:
          ref:
              - refs/heads/main
              - refs/pull/*/head

---
kind: pipeline
name: doc
type: docker

steps:
    - name: build docs
      image: trmckay/rust-riscv64
      commands:
          - make doc
      when:
          event: push
          branch: main
          repo: tm/halogen

    - name: deploy
      image: drillster/drone-rsync
      settings:
          hosts: ["static.trmckay.com"]
          port: 224
          delete: true
          target: /static/halogen/rustdoc
          source: ./kernel/target/riscv64gc-unknown-none-elf/doc/*
          key:
              from_secret: rsync-static-key
      when:
          event: push
          branch: main
          repo: tm/halogen
