kind: pipeline
name: check
type: docker

steps:
    - name: submodules
      image: alpine/git
      commands:
          - git submodule update --init --recursive

    - name: check
      image: trmckay/rust-riscv64
      commands:
          - cargo xtask check
          - cargo xtask build

    - name: test
      image: trmckay/rust-riscv64
      commands:
          - cargo xtask test
