blank_lines_upper_bound = 2
brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"
edition = "2018"
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
force_explicit_abi = true
force_multiline_blocks = true
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
max_width = 100
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
tab_spaces = 4
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
