[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Clink-arg=-Tlink.ld", "--cfg", "platform=\"virt\"", "-g", "--emit=obj,link", "--cfg", "ll_alloc"]

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64 \
    -machine virt \
    -cpu rv64 \
    -m 32M \
    -smp 1 \
    -nographic \
    -serial mon:stdio \
    -bios none \
    -kernel
"""
