name: "Checks"

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure toolchain
      run: rustup default nightly && rustup target add riscv64gc-unknown-none-elf && rustup component add rustfmt
    - name: Check format
      run: make check-format
    - name: Build
      run: make build
