name: Kernel workflow
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install repo dependencies
        run: |
          sudo apt-get update
          sudo apt-get install binutils-riscv64-unknown-elf gcc-riscv64-unknown-elf python3 qemu-system-misc
      - name: Install rustup
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run checks
        run: python3 scripts/build check
