on: [push]

name: CI

jobs:
  riscv-build:
    name: RISC-V rv64gc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: riscv64-unknown-none-elf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target riscv64-unknown-none-elf
